baseURL = "https://mengsselfstorage.netlify.app/"
theme = "PaperMod"

title = "我乐苦多"

[params]
# label.icon = "img/pepsi.jpg"

favicon = "img/pepsi.jpg"

copyright = "© 2025 Suri"
paginate = 5 # Shows 5 posts per page

languageCode = "zh-cn"  # Primary language: Simplified Chinese
defaultContentLanguage = "zh-cn"

ShowShareButtons = true
ShowReadingTime = true
TocOpen = true
ShowToc = true
ShowPostNavLinksn = true
comments = true

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
ignoreErrors = ["error-remote-getjson"]

disqusShortname = ""
googleAnalytics = ""
github = "your_github_username"
linkedin = "your_linkedin_username"
img_home = "img/banner.jpg"  # Add a high-quality image in the 'static/img' folder

[params.homeInfoParams]
Title = "|过一种临时的生活|"
# Content = "过一种临时的生活"

[[params.socialIcons]]
name = "douban"
url = "https://www.douban.com/people/53229181/"

[[params.socialIcons]]
name = "Mastodon"
url = "https://m.cmx.im/@Suri"

[[params.socialIcons]]
name = "RSS"
url = "https://linkedin.com/in/yourprofile"

[outputs]
home = ["HTML", "JSON", "RSS"]

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 200

[[menu.main]]
identifier = "archive"
name = "Archives"
url = "/archives/"
weight = 300

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 400

[[menu.main]]
identifier = "friends"
name = "Friends"
url = "/friends/"
weight = 500

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 600

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 700

